CREATE TABLE IF NOT EXISTS traits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  weight INTEGER DEFAULT 5 CHECK(weight BETWEEN 1 AND 10),
  category TEXT DEFAULT ''
);
